version: '3.8'

services:
  app:
    image: laravelapp
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=gerenciador_viagens
      - DB_USERNAME=root
      - DB_PASSWORD=abc_123456

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: abc_123456
      MYSQL_DATABASE: gerenciador_viagens
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
